# Generated by Django 5.2.2 on 2025-06-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('real_name', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=13, unique=True)),
                ('book_author', models.CharField(max_length=13, unique=True)),
                ('book_status', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField(default=0)),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user')),
            ],
        ),
    ]
