# Generated by Django 5.2.2 on 2025-06-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='Book_ID',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='NULL', max_length=13, unique=True),
        ),
    ]
