# Generated by Django 5.2.2 on 2025-06-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_isbn_book_book_id_remove_book_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('Perm_ID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Perm_name', models.CharField(max_length=50, unique=True)),
                ('Perm_desc', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role_ID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Role_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('order_status', models.CharField(default='待处理', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='index.user')),
                ('book_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.book')),
                ('courier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', to='index.user')),
            ],
        ),
        migrations.CreateModel(
            name='Role_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Perm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.permission')),
                ('Role_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.role')),
            ],
            options={
                'unique_together': {('Role_ID', 'Perm_ID')},
            },
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.role')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user')),
            ],
            options={
                'unique_together': {('User_ID', 'Role_ID')},
            },
        ),
    ]
