# Generated by Django 5.2.2 on 2025-06-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_permission_role_order_role_permission_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='Role_name',
        ),
    ]
