# Generated by Django 5.2.2 on 2025-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_role_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='Role_name',
            field=models.CharField(choices=[('管理员', '管理员'), ('派送员', '派送员'), ('学生', '学生')], default='NULL', max_length=10),
        ),
    ]
