# Generated by Django 5.2.2 on 2025-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Role_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
