# Generated by Django 5.2.2 on 2025-06-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_role_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='studentid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
    ]
