# Generated by Django 5.2.2 on 2025-06-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_rename_phone_user_studentid_remove_user_real_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='studentid',
            new_name='student_id',
        ),
    ]
