# Generated by Django 5.2.2 on 2025-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_rename_studentid_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(default='小明', max_length=10, unique=True),
        ),
    ]
