# Generated by Django 5.2.2 on 2025-06-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
