# Generated by Django 5.2.2 on 2025-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Role_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
