# Generated by Django 5.2.2 on 2025-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_role_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='NULL', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='Perm_ID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='Role_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(default='小明', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
