# Generated by Django 5.2.2 on 2025-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_book_book_author_alter_book_bookname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(default='username', max_length=30),
        ),
    ]
