# Generated by Django 5.2.2 on 2025-06-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role_permission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='user_role',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
